<?xml version="1.0"?>
<package format="3">
  <name>robot_slam</name>
  <version>0.0.1</version>
  <description>SLAM for Echo Plus + Livox</description>
  <maintainer email="you@email.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>livox_ros_driver2</exec_depend>
  <exec_depend>xpkg_demo</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
