# shared/config.yaml
ros2:
  topics:
    rgb_camera_raw: "/aria/rgb_camera/raw"
    rgb_camera_undistorted: "/aria/rgb_camera/undistorted"
    slam_left_raw: "/aria/slam_left/raw"
    slam_right_raw: "/aria/slam_right/raw"
    eye_tracking_raw: "/aria/eye_tracking/raw"
    eye_tracking_gaze_estimate: "/aria/eye_tracking/gaze_estimate"
    rgb_camera_with_object_masks: "/aria/rgb_camera/object_masks"
    ros_camera_with_object_masks: "/realman/rgb_camera/object_masks"
    combined_visualization: "/combined/object_masks"
    feature_match_results: "/aria/rgb_camera/feature_match"
    audio_transcription_prompt: "/aria/audio/prompt"
    imu: "/aria/imu"
    aruco_pose: "/aria/aruco_pose"
    vio_pose: "/aria/vio_pose"
    fused_pose: "/aria/fused_pose"
    is_stationary: "/aria/is_stationary"

  qos:
    video:
      reliability: "BEST_EFFORT"
      history: "KEEP_LAST"
      depth: 10